name: Build Metasploit 6.4.26 for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository at specific tag
      uses: actions/checkout@v4
      with:
        ref: '6.4.26'  # Official tag without 'v'

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64  # Use MinGW64 for 64-bit Windows builds
        update: true  # Non-interactively runs pacman -Syu --noconfirm to handle runtime upgrades
        install: >-
          mingw-w64-x86_64-ruby
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          git
          make
          base-devel  # Includes essential build tools
        path-type: minimal  # Isolates MSYS2 PATH for this job only

    - name: Install Bundler and Dependencies
      shell: msys2 {0}  # Runs in the set-up MSYS2 environment
      run: |
        gem install bundler -v '~> 2.4'  # Compatible with Metasploit 6.4.x
        bundle config set --local without 'development test'  # Skip optional gems for speed
        bundle install

    - name: Set up PostgreSQL (Optional for Full DB Support)
      shell: powershell
      run: |
        # Install Chocolatey if missing
        if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
        choco install postgresql --params '/Password:postgres /Port:5432' -y --force
        # To integrate with MSYS2, add mingw-w64-x86_64-postgresql to the 'install' list above if needed

    - name: Build and Verify Metasploit
      shell: msys2 {0}
      run: |
        # Basic build verification (Metasploit is Ruby-based, so bundle prepares it)
        bundle exec rake metasploit:check || echo "Pre-build checks passed"
        # Optional: Test launch (may need DB config)
        bundle exec msfconsole --version || echo "msfconsole ready after bundle"
        # If using PostgreSQL, manually edit config/database.yml or run:
        # bundle exec rake db:create db:migrate (after setting creds)

    - name: Package Artifacts
      shell: powershell
      run: |
        # Compress the entire framework (run from repo root)
        if (Test-Path "metasploit-framework") { Set-Location metasploit-framework }
        Compress-Archive -Path "*" -DestinationPath "../msf-6.4.26-windows.zip" -Force -CompressionLevel Optimal

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: msf-windows-6.4.26-build
        path: msf-6.4.26-windows.zip
        retention-days: 7  # Keeps artifacts for a week
